apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: dmpjwp.b04m9uk5mghi7r3l
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.1.56
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
  imagePullPolicy: IfNotPresent
  name: pi7
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: k8s.jayflory.net:6443
controllerManager:
  extraArgs:
    node-cidr-mask-size: "24"
etcd:
  external:
    caFile: /etc/kubernetes/etcd/ca.crt
    certFile: /etc/kubernetes/etcd/client.crt
    keyFile: /etc/kubernetes/etcd/client.key
    endpoints:
    - https://192.168.1.40:2379
    - https://192.168.1.41:2379
    - https://192.168.1.42:2379
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: v1.28.0
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}